### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by mclearc** [yantar92/org#38] opened 2021-11-23 16:40 UTC
**Describe the bug**

I'm seeing the following in various org files:

```emacs-lisp
 The error was: (error "rx ‘**’ range error")
 Backtrace:
"  backtrace-to-string(nil)
  org-element-at-point()
  org-element-context()
  org-appear--current-elem()
  org-appear--post-cmd()
"
```

**Expected behavior**

I expected to just be able to fold or unfold headlines as usual.

**To Reproduce**

I haven't yet been able to reproduce this in a clean config, nor have I been able to pinpoint what it is about my normal config that might be causing the issue. But I'll keep looking. In the meantime, any advice is appreciated. Thanks for your work.

**Comment by mclearc** [comment] 2021-11-23 16:44
Ah - ok, maybe this is related to org-appear issue 5? https://github.com/awth13/org-appear/issues/5

I'm going to switch to the org-fold support branch and see if that resolves the cache issue. Will close this if so. Thanks!

**Comment by mclearc** [comment] 2021-11-23 17:49
Ok -- it does not seem to be related to org-appear. Here's another statement of the bug with that package disabled:

```emacs-lisp
Warning (emacs): org-element--cache: Cache corruption detected in inbox.org. Resetting.
 The error was: (error "rx ‘**’ range error")
 Backtrace:
"  backtrace-to-string(nil)
  org-element-at-point()
  org-cycle(nil)
  funcall-interactively(org-cycle nil)
  command-execute(org-cycle)
  recursive-edit()
  org-goto-location()
  org-goto(nil)
  funcall-interactively(org-goto nil)
  command-execute(org-goto record)
  execute-extended-command(nil \"org-goto\" \"org goto\")
  funcall-interactively(execute-extended-command nil \"org-goto\" \"org goto\")
  command-execute(execute-extended-command)
"
```

**Comment by yantar92** [comment] 2021-11-24 00:10
> Warning (emacs): org-element--cache: Cache corruption detected in inbox.org. Resetting.
>  The error was: (error "rx ‘**’ range error")

Are you using the latest version? 17d4b31a8 supposed to fix this error.

**Comment by mclearc** [comment] 2021-11-24 01:57
Yeah I rebuilt the package this morning so I'm up to 3c7f8a

**Comment by yantar92** [comment] 2021-11-24 03:08
> Yeah I rebuilt the package this morning so I'm up to 3c7f8a

Then, can you set `org-element--cache-self-verify` to 'backtrace and
report the full warning message (possibly stripping sensitive data) next
time you see the warning?

**Comment by mclearc** [comment] 2021-11-26 02:18
Having set the self-verify setting I'm getting:

```emacs-lisp
 Warning (emacs): org-element--cache: Cache corruption detected in xxxxx.org. Resetting.
 The error was: (error "rx ‘**’ range error")
 Backtrace:
nil
 Please report this to Org mode mailing list (M-x org-submit-bug-report). Disable showing Disable logging
```

**Comment by yantar92** [comment] 2021-11-26 10:44
Colin McLear ***@***.***> writes:

> Having set the self-verify setting I'm getting:
>
> ```emacs-lisp
>  Warning (emacs): org-element--cache: Cache corruption detected in xxxxx.org. Resetting.
>  The error was: (error "rx ‘**’ range error")
>  Backtrace:
> nil
>  Please report this to Org mode mailing list (M-x org-submit-bug-report). Disable showing Disable logging
> ```

Don't you also have a long second backtrace below? Can you confirm that
the value of org-element--cache-self-verify to `backtrace` symbol and
you set it in your init file?

P.S. I have also seen this error 2 days ago, but cannot reproduce any
more. A full backtrace would help a lot.

**Comment by mclearc** [comment] 2021-11-26 17:08
Yep -- have the setting correct but it just says "nil". See the screenshots below. I'm on the emacs master branch (29.0.5) if that is important. 
<img width="883" alt="Screen Shot 2021-11-26 at 12 04 10" src="https://user-images.githubusercontent.com/1502422/143613500-4061a3a4-713f-4318-984e-41ad386ff53f.png">
<img width="868" alt="Screen Shot 2021-11-26 at 12 02 58" src="https://user-images.githubusercontent.com/1502422/143613517-29774f61-2701-41e0-bb3b-101e625ddbb1.png">

**Comment by yantar92** [comment] 2021-11-27 04:26
Colin McLear ***@***.***> writes:

> Yep -- have the setting correct but it just says "nil". See the screenshots below. I'm on the emacs master branch (29.0.5) if that is important. 

It implies that the error is not triggered by cache, but rather a bug in
Org parser.

I just pushed a change that will provide additional info
(current buffer point) in the warning you are seeing.

Can you
1. try to set org-element-use-cache to nil in your config and
   see if you are still getting the error.
2. If you do, go to the buffer point reported in the warning, and
   manually run M-: (org-element--parse-to <the point>) <RET>
3. If you get error now, post the problematic heading down to
   <the point>

**Comment by mclearc** [comment] 2021-11-27 18:51
I should also say that `org-element-use-cache` had been set to `nil` all along. But I'll let you know if I see the error again, and the info gathered when following (2) and (3) as you say. Thanks for the help!

**Comment by mclearc** [comment] 2021-11-27 23:47
I'm seeing this error in an elisp file where I use outline to fold headings with `;;;`, etc. Here's the backtrace:

```emacs-lisp
 Warning (org-element-cache): org-element--cache: Cache corruption detected in setup-citation.el::7126. Resetting.
 The error was: (error "rx ‘**’ range error")
 Backtrace:
"  backtrace-to-string(nil)
  org-element-at-point()
  org-element-context()
  org-cite-insert(nil)
  funcall-interactively(org-cite-insert nil)
  command-execute(org-cite-insert)
"
 Please report this to Org mode mailing list (M-x org-submit-bug-report). Disable showing Disable logging
```

And the more detailed backtrace:

```emacs-lisp
Debugger entered--Lisp error: (error "rx ‘**’ range error")
  error("rx `%s' range error" **)
  rx--translate-bounded-repetition(** (1 0 "*"))
  rx--translate-**((1 0 "*"))
  rx--translate-form((** 1 0 "*"))
  rx--translate((** 1 0 "*"))
  rx--translate-seq((line-start (** 1 0 "*") " "))
  rx--translate-form((seq line-start (** 1 0 "*") " "))
  rx--translate((seq line-start (** 1 0 "*") " "))
  rx-to-string((seq line-start (** 1 0 "*") " "))
  org-element-headline-parser(nil fast)
  org-element--parse-to(7126)
  eval-expression((org-element--parse-to 7126))
  eval((eval-expression (car-safe (read-from-string #("(org-element--parse-to 7126)" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6) 6 7 (ex-index 7) 7 8 (ex-index 8) 8 9 (ex-index 9) 9 10 (ex-index 10) 10 11 (ex-index 11) 11 12 (ex-index 12) 12 13 (ex-index 13) 13 14 (ex-index 14) 14 15 (ex-index 15) 15 16 (ex-index 16) ...)))))
  evil-ex-execute(#("(org-element--parse-to 7126)" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6) 6 7 (ex-index 7) 7 8 (ex-index 8) 8 9 (ex-index 9) 9 10 (ex-index 10) 10 11 (ex-index 11) 11 12 (ex-index 12) 12 13 (ex-index 13) 13 14 (ex-index 14) 14 15 (ex-index 15) 15 16 (ex-index 16) ...))
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  command-execute(evil-ex)
```

**Comment by yantar92** [comment] 2021-11-28 00:12
> I should also say that `org-element-use-cache` had been set to `nil` all along.

<offtopic>It makes me wonder why you are using this repo. The whole
point of it  is performance improvement and cache is a big part of it</offtopic>

**Comment by mclearc** [comment] 2021-11-28 00:14
> I should also say that `org-element-use-cache` had been set to `nil` all along.
> <offtopic>It makes me wonder why you are using this repo. The whole point of it is performance improvement and cache is a big part of it</offtopic>

folding had been very slow so I thought I would give it (i.e. your fork) a try (I also hadn't noticed I had turned the cache off awhile ago because of a separate error that had been coming up 🤷 )

**Comment by yantar92** [comment] 2021-11-28 00:24
> I'm seeing this error in an elisp file where I use outline to fold headings with `;;;`, etc. Here's the backtrace:
> ...
>  Warning (org-element-cache): org-element--cache: Cache corruption detected in setup-citation.el::7126. Resetting.
> ...
>   command-execute(org-cite-insert)

Err... But why are you calling an org command in non-org buffer? No
wonder you are getting the error.

Note that the backtrace shows that you did not try to fold Elisp heading
using outline-mode, but somehow called `org-cite-insert`.

In the above messages you reported an error in proper org buffer though.
What you are seeing here is some _different_ and seemingly unrelated
error. I opened another bug report for this last issue you are seeing.

Please report errors in actual Org buffers in this thread.

**Comment by mclearc** [comment] 2021-11-28 00:28
> Err... But why are you calling an org command in non-org buffer? No wonder you are getting the error. Note that the backtrace shows that you did not try to fold Elisp heading using outline-mode, but somehow called `org-cite-insert`. In the above messages you reported an error in proper org buffer though. What you are seeing here is some _different_ and seemingly unrelated error.

Yeah - I wasn't calling that function intentionally so I'm not sure what happened there...

> I opened another bug report for this last issue you are seeing. Please report errors in actual Org buffers in this thread.

will do

**Comment by yantar92** [comment] 2021-11-28 00:31
> folding had been very slow so I thought I would give it a try (I also hadn't noticed I had turned the cache off awhile ago because of a separate error that had been coming up 🤷 )

Got it. Note that cache is enabled by default upstream after I merged
the cache-related commits to Org mode master.

The folding part of this branch is actually waiting to be merged after
cache- and parser-related bugs (like what we have here) become less
frequent.

**Comment by mclearc** [comment] 2021-11-30 16:59
Another error:

```emacs-lisp
Warning (org-element-cache): org-element--cache: Cache corruption detected in phil232-class-plan.org::133. Resetting.
 The error was: (error "rx ‘**’ range error")
 Backtrace:
nil
 Please report this to Org mode mailing list (M-x org-submit-bug-report). Disable showing Disable logging
```

And the longer backtrace:

```emacs-lisp
Debugger entered--Lisp error: (error "rx ‘**’ range error")
  error("rx `%s' range error" **)
  rx--translate-bounded-repetition(** (1 0 "*"))
  rx--translate-**((1 0 "*"))
  rx--translate-form((** 1 0 "*"))
  rx--translate((** 1 0 "*"))
  rx--translate-seq((line-start (** 1 0 "*") " "))
  rx--translate-form((seq line-start (** 1 0 "*") " "))
  rx--translate((seq line-start (** 1 0 "*") " "))
  rx-to-string((seq line-start (** 1 0 "*") " "))
  org-element-headline-parser(132 t)
  org-element--current-element(132 element nil nil)
  org-element--parse-to(133)
  eval-expression((org-element--parse-to 133))
  eval((eval-expression (car-safe (read-from-string #("(org-element--parse-to 133)" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6) 6 7 (ex-index 7) 7 8 (ex-index 8) 8 9 (ex-index 9) 9 10 (ex-index 10) 10 11 (ex-index 11) 11 12 (ex-index 12) 12 13 (ex-index 13) 13 14 (ex-index 14) 14 15 (ex-index 15) 15 16 (ex-index 16) ...)))))
  evil-ex-execute(#("(org-element--parse-to 133)" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6) 6 7 (ex-index 7) 7 8 (ex-index 8) 8 9 (ex-index 9) 9 10 (ex-index 10) 10 11 (ex-index 11) 11 12 (ex-index 12) 12 13 (ex-index 13) 13 14 (ex-index 14) 14 15 (ex-index 15) 15 16 (ex-index 16) ...))
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  command-execute(evil-ex)
```

And the file to point 133:

```
#+TITLE: PHIL 232 Class Plan
#+DATE: SPRING 2019 

* Students

* Assignments
** Quizzes
** Paper
** Midterm
** Final
** Discussion
* Module Plan
** Descartes's Rationalist Project
*** Overview: Descartes's Rationalism
In this module we look at the philosophical system of Rene Descartes.  

The objectives for this module are to:

1. *Understand* Descartes's rationalist project
2. *Explain* the various components of Descartes's philosophical system including:
    - The nature and importance of method in science
    - The role of skepticism in philosophy
    - The rejection of scholasticism
    - The relation between the intellect and the senses
    - The relation between self-consciousness and certainty
    - The nature of mind and body and their independence

To satisfy these objectives I'm asking you to:

A. *Read* the various assigned readings; I'll also include various optional readings,
   as well as my notes for lecture
B. *Watch* short video lectures 
C. *Answer* short quizzes
D. *Ask* questions in a weekly discussion board
E. *Attend* a weekly synchonous zoom meeting on Thursdays

All of the readings will either be posted here in Canvas or from one of your required
books. Other notes and materials will all be posted here.
*** The Scholastic Aristotelian Background

*** Descartes's Background & Method
*** Skepticism & Empiricism: First Meditation
*** Quiz 1
1. What are the four rules in Descartes's "method" for acquiring
   knowledge? 
   - Don't accept as true without evidence; Provide a standard of correctnesss
   - Reduce complex problems to their simplest components
   - Solve from the simple to the complex
   - Review your work and leave no gaps
2. What is epistemic foundationalism?
   - There is a class of privileged knowledge upon which all other knowledge depends
3. (T/F) Descartes's method of doubt requires that we believe all of our beliefs
   are false 
   - One must suspend judgment concerning anything about which one cannot be completely certain
4. Why does Descartes employ his method of doubt?
   - To construct a science that is "stable and likely to last"
5. Name one of the stages of doubt
   - Sense deception
   - Dreams
   - The evil demon

*** The Cogito & the Intellect: Second Meditation
*** Quiz 2
1. What is the "cogito" argument? 
2. Name one way in which the argument is problematic 
3. What does Descartes assume is entailed by the existence of a thought?
4. T/F: The Meditator claims that it can be certain that it is a "thinking thing"? 
5. T/F: The wax argument shows that body is known via the senses only 

*** God & Certainty: Third Meditation
*** Quiz 3
1. Name one source of our ideas that Descartes discusses
   - adventitious
   - invented
   - innate
2. T/F: Descartes needs to prove that God exists to be certain that the /cogito/
   is true
   - F
3. T/F: The truth rule states that whenever one thinks, what one thinks is true
   - F
4. T/F: The Med 2 wax argument presupposes that bodies exist
   - F
5. What is the formal reality of an idea?
   - its existence as a mode of the mind

*** Freedom & Error: Fourth Meditation

*** Quiz 4
1. In Med 3 Descartes articulates 2 proofs of the existence of God. Name one.
   - causal argument from idea of god
   - from preservation/conservation of finite beings
2. In his first proof of God’s existence D uses a metaphysical principle. Name
   the principle & briefly describe its content
   - causal principle: an effect cannot contain more reality than its efficient
     and total cause
3. T/F: Descartes explain the existence of error as arising because of the
   relation between the imagination and the understanding
   - F
4. T/F: Descartes thinks that finite substances lack the power to persist
   through time on their own 
   - T
5. T/F: Descartes thinks that the power to preserve is the same the as the power
   to create
   - T

*** Esssence & Existence: Fifth Meditation
*** The Real Distinction Argument: Sixth Meditation
*** Quiz 5
1. Name one of the three kinds of distinctness
   - conceptual/modal/real
2. What are the two "arcs" or claims of the Cartesian Circle?
   - I can be certain of P only if I can be certain that Q/ I can be certain
     of Q only if I can be certain that P
   P=whatever I C&D perceive is true
   Q=God exists and is not a deceiver
3. T/F: According to Van Cleve's solution to the circle, Descartes must prove
   that general epistemic principles hold before he can prove that we have
   knowledge of particular truths. 
   - F
4. In the 5th med D argues that what controversial feature is part of God's essence?
   - existence
5. T/F: According to D in the 5th med the essence of matter is solidity
   - F; extension


*** The Problem of Interaction: Correspondence with Princess Elisabeth

*** Quiz 6
1. 
   
** Problems with Mechanism & Materialism

*** Overview: Problems for Materialism
```

**Comment by yantar92** [comment] 2021-12-02 01:22
> And the file to point 133:

This was helpful. Thanks! Should be fixed now.

**Comment by darosio** [comment] 2021-12-02 12:09
I am experiencing this after adding to init.el the following:
  (use-package ob-exp
	:straight nil
	:config (setq org-export-use-babel nil))

**Closed as completed** 2021-12-05 14:04 UTC
Labels: bug
